### ISSUE TITLE
Lexer uses nth 

### ISSUE THREAD

**Issue by DanCardin** [TheDan64/limonite#16]
O(n) operation when it could be O(1) if we were iterating rather than trying to directly index each char

**Comment by TheDan64** [comment]
We could go back to using the unstable char_at() [which I read was O(1)](https://www.reddit.com/r/rust/comments/30c6yb/why_is_accessing_a_char_from_a_str_so_annoying/cpr2cu2).

**Comment by DanCardin** [comment]
But doesn't work with utf8 characters. The inefficiency isn't a big deal at this point, it's just something we stop doing at some point

**Comment by TheDan64** [comment]
Works fine with utf8 chars: http://is.gd/oM2Iuk

**Comment by TheDan64** [comment]
Counter-example: http://is.gd/dmXU4t

**Comment by TheDan64** [comment]
If we use an iterator (as opposed to a vector) there is the [peekable iterator](http://doc.rust-lang.org/nightly/std/iter/trait.IteratorExt.html#tymethod.peekable).
