### ISSUE TITLE
Tokens and Exprs should use str slices from the original input String

### ISSUE THREAD

**Issue by TheDan64** [TheDan64/limonite#38]
Currently we're creating new Strings which I believe allocates more memory. The ideal but difficult optimization is to use slices from the original String but would probably require a lot of rework to get associated lifetimes to work together.

**Comment by TheDan64** [comment]
Tried taking a shot at this again this weekend and I think we might need the lexer to be a streaming iterator, which I don't believe rust has support for yet.

**Comment by DanCardin** [comment]
nope. because existing parsers already do this.

**Comment by TheDan64** [comment]
You say that, but, I've got it down to two errors and the compiler is suggesting that I have to/should add a lifetime to the next() method, but that would require a streaming iterator.

**Comment by TheDan64** [comment]
Possible solution: https://github.com/servo/tendril

**Comment by TheDan64** [comment]
According to [this thread](https://www.reddit.com/r/rust/comments/6ha6qa/rust_equivalent_to_character_stream/diwxn0y/), it seems like our main problem is that we're using the lexer as an iterator when instead we should have one big preallocated string which the lexer could just hand out (COW) slices to?

**Comment by TheDan64** [comment]
This is done in `features/new` which will be merged into master soon
